### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by paul-sachs**
## What's Changed
* Add a distinguishing factor between infinite query keys and regular query keys by @paul-sachs in https://github.com/connectrpc/connect-query-es/pull/334
* Add support for enabled to useInfiniteQuery by @paul-sachs in https://github.com/connectrpc/connect-query-es/pull/338

## Changes to infinite query keys

With https://github.com/connectrpc/connect-query-es/pull/334, we're fixing a bug where the cache of a regular query collides with the cache of an infinite query, which can lead to type mismatches and unexpected failures if you use the same RPC with an infinite query and a regular query.
We are now using a separate query key for infinite queries to solve the issue (we append "infinite" to the key), but this change can potentially affect you:

If you tried to invalidate some infinite queries like `queryClient.invalidateQueries({ queryKey: createConnectQueryKey(...), exact: true })`, this now only invalidates queries initialized with `useQuery`. To invalidate infinite queries, you can either set `exact` to false, or use `createConnectInfiniteQueryKey()` instead. Also note that this change not only affects `invalidateQueries` but any operations against the queryClient that interact with the cache using a key (eg, queryClient.setQueriesData, etc.)

**Full Changelog**: https://github.com/connectrpc/connect-query-es/compare/v1.1.3...v1.2.0

### CODE REVIEW

**Comment by paul-sachs** [comment]
This **may** be worth an update to 2.0 since it does change the way data is stored within react-query cache. Feels like a lot more churn than it's worth however.

**Comment by timostamm** [comment]
> there may be some breakages when using the createConnectQueryKey along with queryClient 

Can you elaborate what this means?

**Comment by paul-sachs** [comment]
@timostamm update description with an example.

**Comment by timostamm** [comment]
Thanks. You mentioned in https://github.com/connectrpc/connect-query-es/issues/328#issuecomment-1932252394:

> having infinite queries share the same key as a regular query leads to very possible type mismatches and unexpected failures

So it's an important bug to fix. The change in behavior you describe is IMO acceptable in order to fix this bug.

I suggest to explain this situation in the release notes, for example:

 > With https://github.com/connectrpc/connect-query-es/pull/334, we're fixing a bug where the cache of a regular query collides with the cache of an infinite query, which can lead to type mismatches and unexpected failures if you use the same RPC with an infinite query _and_ a regular query.
> We are now using a separate query key for infinite queries to solve the issue (we append `"infinite"` to the key), but this change can potentially affect you: If you tried to invalidate...

**Comment by paul-sachs** [comment]
@timostamm awesome suggestion. I've also added a bit making sure it's clear that it's not just `invalidateQueries` that is affected.

**Pull request merged**
