### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by paul-sachs**
## What's Changed
* Update imports to include file extensions by @paul-sachs in https://github.com/connectrpc/connect-query-es/pull/299 and https://github.com/connectrpc/connect-query-es/pull/307
* Added support for cjs output by @paul-sachs in https://github.com/connectrpc/connect-query-es/pull/303
* Loosen peer dependency requirement by @paul-sachs in https://github.com/connectrpc/connect-query-es/pull/306

## CJS output

By default, [protoc-gen-connect-query](https://www.npmjs.com/package/@connectrpc/protoc-gen-connect-query) (and all other plugins based on [@bufbuild/protoplugin](https://www.npmjs.com/package/@bufbuild/protoplugin)) generate ECMAScript `import` and `export` statements. For use cases where CommonJS is difficult to avoid, a new plugin option has been added named `js_import_style` which can be used to generate CommonJS `require()` calls.

Here is an example [buf.gen.yaml](https://buf.build/docs/configuration/v1/buf-gen-yaml):

```yaml
version: v1
plugins:
  # You'll need @bufbuild/protoc-gen-es v1.6.0 or later
  - plugin: es
    out: src/gen
    opt: js_import_style=legacy_commonjs
  - plugin: protoc-gen-connect-query
    out: src/gen
    opt: js_import_style=legacy_commonjs
```

To view the full PR, see **Added support for cjs output** by @paul-sachs in https://github.com/connectrpc/connect-query-es/pull/303

**Full Changelog**: https://github.com/connectrpc/connect-query-es/compare/v1.0.0...v1.1.0

### CODE REVIEW

**Comment by paul-sachs** [comment]
Wasn't sure if we would include the changes to fix imports in `create-react-app` (ie, the import extensions) as externally visible changes. It's not an API change but it does fix compat for some bundlers.

**Comment by nicksnyder** [comment]
> Added support for cjs output by

This feels like a feature so wouldn't a version of `1.1.0` be more appropriate?

**Comment by paul-sachs** [comment]
@nicksnyder ah, yeah that's fair.

**Comment by timostamm** [comment]
Missed it earlier, sorry, but can we add `js_import_style` to the [ToC of the plugin readme](https://github.com/connectrpc/connect-query-es/blob/3b26f474fd06fd6064dab7f7b62b043b788b7441/packages/protoc-gen-connect-query/README.md?plain=1#L15)?

**Comment by paul-sachs** [comment]
@timostamm Yep, added here: https://github.com/connectrpc/connect-query-es/pull/309.

**Review by timostamm — APPROVED** [review]

**Pull request merged**
