### PR TITLE
Remove experimental plugin

### PR DESCRIPTION
**Pull request by paul-sachs**
`@tanstack/react-query` v5 is introducing some major changes to their types and also introduce suspense specific APIs (useSuspenseQuery, useSuspenseInfiniteQuery, and useSuspenseQueries). These APIs are pretty easy to integrate with the original plugin (non-react specific) but would need an additional two APIs generated for every service method. This starts to create a lot of noise with our auto-complete options:

As an example, if we have a service method called `say`, we now must generate `useSayQuery`, `useSayInfiniteQuery`, `useSayMutation`, `useSaySuspenseQuery`, and `useSaySuspenseInfiniteQuery`. This is increasingly making a lot of noise when just trying to use the `say` method from a service. This is much worse with larger service method names.

In keeping with best practices (limiting the number of ways to do a single thing), we've decided to remove this plugin from the repo.

### CODE REVIEW

**Comment by paul-sachs** [comment]
@vctqs1 After experimenting with this plugin, we've decided to remove it to simplify the offerings. Obviously you can fork and maintain the plugin yourself, but in order to maintain the API for v5 of react-query, we're going to keep to the original plugin as the primary means of generating helpers.

**Review by timostamm — APPROVED** [review]

**Comment by vctqs1** [comment]
@paul-sachs hi, sorry, but Could I publish this experiment plugin in my own? Is it `illegal`?

**Comment by paul-sachs** [comment]
@vctqs1 yes, you can most certainly publish your own plugin and package. Feel free to form the repo.

**Comment by vctqs1** [comment]
@paul-sachs thank you 👍🏻

**Comment by paul-sachs** [comment]
@vctqs1 I thought you might be interested in #220. It's proposing a simplified API, but with full support of the expanded tanstack/react-query@v5 API.

**Comment by vctqs1** [comment]
@paul-sachs ohm thank you, im currently working on  **Tanstack v4**. Because of some breaking changes of onError/onSuccess in v5, it's make me afraid to upgrade version for now
It'd be great as https://github.com/connectrpc/connect-query-es/issues/220 said, we might support parallel and migrator for both versions

I also noticed about tree-shaking problem in current source. Yeah, but glad to heard that your team're gonna to do an enhancement on this proposal also.

Please help me know and loop on any update on this proposal, and progressing. Thank you

**Pull request merged**
